# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.15.+

# Dependencies
fabric_version=0.160.5+26.3
plasmid_version=0.7.3-SNAPSHOT+26.3

# Mod Properties
mod_version=1.0.0
maven_group=io.github.restioson
archives_base_name=koth
